In [1]:
import pandas as pd
import numpy as np

In [5]:
my_series =pd.Series([1,2,3,"string",4.5])

In [6]:
my_series

0         1
1         2
2         3
3    string
4       4.5
dtype: object

In [8]:
type(my_series)

pandas.core.series.Series

In [18]:
import pandas as pd
import os
os.getcwd()

'C:\\Users\\Jisha Manjesh.DESKTOP-J86V7RQ'

In [19]:
df=pd.read_csv("SalesKaggle3.csv")
df

,Order,File_Type,SKU_number,SoldFlag,SoldCount,MarketingType,ReleaseNumber,New_Release_Flag,StrengthFactor,PriceReg,ReleaseYear,ItemCount,LowUserPrice,LowNetPrice
0,2,Historical,1737127,0.0,0.0,D,15,1,6.827430e+05,44.99,2015,8,28.97,31.84
1,3,Historical,3255963,0.0,0.0,D,7,1,1.016014e+06,24.81,2005,39,0.00,15.54
2,4,Historical,612701,0.0,0.0,D,0,0,3.404640e+05,46.00,2013,34,30.19,27.97
3,6,Historical,115883,1.0,1.0,D,4,1,3.340110e+05,100.00,2006,20,133.93,83.15
4,7,Historical,863939,1.0,1.0,D,2,1,1.287938e+06,121.95,2010,28,4.00,23.99
5,8,Historical,214948,0.0,0.0,D,0,0,1.783153e+06,132.00,2011,33,138.98,13.64
6,9,Historical,484059,0.0,0.0,D,13,1,2.314801e+06,95.95,2010,33,90.77,46.49
7,10,Historical,146401,0.0,0.0,D,4,1,7.211110e+05,207.80,2011,57,187.90,30.56
8,11,Historical,110568,0.0,0.0,D,11,1,4.366670e+05,119.81,2008,36,63.99,96.92
9,12,Historical,764270,0.0,0.0,D,5,1,6.652211e+06,49.95,2004,19,53.99,28.99
10,13,Historical,1597828,0.0,0.0,D,9,1,1.613480e+05,36.95,2008,21,0.00,27.98
11,14,Historical,178736,0.0,0.0,D,4,1,3.005118e+06,55.95,2010,16,34.51,11.52
12,15,Historical,525904,0.0,0.0,D,10,1,1.785056e+06,104.99,2010,15,4.39,73.89
13,16,Historical,3016759,0.0,0.0,D,2,1,4.323581e+06,0.00,1994,26,0.00,61.85
14,17,Historical,169222,0.0,0.0,D,8,1,2.352021e+06,129.95,2006,22,75.84,8.97
15,18,Historical,3071053,0.0,0.0,D,5,1,7.693526e+06,64.95,2005,12,128.99,37.39
16,19,Historical,110699,1.0,1.0,D,6,1,3.831290e+05,120.39,2007,69,170.45,78.99
17,20,Historical,115159,0.0,0.0,D,1,0,9.098310e+05,126.20,2001,33,38.92,44.46
18,21,Historical,143125,0.0,0.0,D,9,1,2.798929e+06,167.75,2006,20,6.97,28.49
19,22,Historical,144296,0.0,0.0,D,2,1,2.491442e+06,94.60,2001,33,11.23,4.99
20,23,Historical,159588,0.0,0.0,D,2,1,1.315627e+06,53.95,2007,37,9.93,15.89
21,24,Historical,178701,0.0,0.0,D,0,0,1.814079e+06,399.95,2012,34,71.79,91.90
22,25,Historical,210839,1.0,1.0,D,1,0,1.568054e+06,42.95,2001,23,57.94,18.99
23,26,Historical,210920,0.0,0.0,D,1,0,5.499900e+04,97.95,2009,34,42.35,63.98
24,27,Historical,2387463,1.0,1.0,D,6,1,2.701930e+05,0.00,1979,22,141.98,76.22
25,28,Historical,2398402,1.0,1.0,D,2,1,1.566380e+05,98.95,1988,67,142.71,14.02
26,29,Historical,244942,1.0,1.0,D,9,1,1.160035e+06,177.95,2003,52,45.80,9.99
27,30,Historical,247825,0.0,0.0,D,2,1,2.450935e+06,51.95,2004,46,57.89,12.49
28,31,Historical,251957,0.0,0.0,D,3,1,1.728372e+06,70.95,2009,47,7.47,4.00
29,32,Historical,3133247,0.0,0.0,D,4,1,2.925930e+06,50.00,2001,14,112.86,59.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198887,207998,Active,1556695,NaN,NaN,S,1,0,1.874855e+05,47.95,2014,34,39.35,35.32
198888,207999,Active,177923,NaN,NaN,D,3,1,7.735933e+05,157.95,2003,78,4.00,7.15
198889,208000,Active,524948,NaN,NaN,S,4,1,5.804377e+04,151.95,2012,51,38.67,69.49
198890,208001,Active,1557959,NaN,NaN,S,0,0,1.964078e+05,47.95,2015,37,38.95,38.39
198891,208002,Active,132327,NaN,NaN,S,2,1,9.047473e+05,47.95,2007,50,4.00,43.68
198892,208003,Active,1703720,NaN,NaN,S,0,0,1.724417e+04,75.00,2010,39,36.78,45.83
198893,208004,Active,750629,NaN,NaN,D,1,0,9.148262e+05,49.99,2008,40,4.74,14.98
198894,208005,Active,617572,NaN,NaN,S,2,1,5.796935e+05,49.99,2011,26,43.67,60.98
198895,208006,Active,3604374,NaN,NaN,D,4,1,3.118201e+06,24.25,1900,11,30.15,31.61
198896,208007,Active,2347080,NaN,NaN,D,7,1,1.974106e+06,185.00,1992,25,5.98,39.49
198897,208008,Active,524944,NaN,NaN,D,9,1,3.558298e+05,299.00,2010,61,61.84,103.78
198898,208009,Active,105697,NaN,NaN,S,8,1,1.227734e+06,245.00,2002,19,40.90,98.99
198899,208010,Active,140589,NaN,NaN,S,4,1,5.082790e+04,37.99,2011,59,11.86,18.86
198900,208011,Active,140391,NaN,NaN,S,3,1,2.091045e+05,39.99,1999,120,4.00,17.83
198901,208012,Active,1497601,NaN,NaN,S,0,0,2.519505e+04,44.99,2011,27,26.03,26.26
198902,208013,Active,524940,NaN,NaN,S,0,0,3.559156e+04,49.99,2011,36,15.75,24.85
198903,208014,Active,524941,NaN,NaN,S,0,0,5.635351e+03,36.99,2011,39,16.62,20.83
198904,208015,Active,327486,NaN,NaN,S,0,0,1.868270e+05,39.99,2008,43,7.97,65.11
198905,208016,Active,775022,NaN,NaN,D,4,1,1.035268e+06,99.00,1999,21,55.53,189.92
198906,208017,Active,128752,NaN,NaN,D,1,0,4.948711e+05,55.00,2009,21,11.49,73.97
198907,208018,Active,2265700,NaN,NaN,D,2,1,8.756080e+06,111.14,2009,21,24.84,92.30
198908,208019,Active,861845,NaN,NaN,S,2,1,2.031828e+05,59.95,2013,21,44.14,44.03
198909,208020,Active,863599,NaN,NaN,S,2,1,1.466957e+05,64.99,2008,34,41.83,53.00
198910,208021,Active,614304,NaN,NaN,S,6,1,6.078198e+05,21.50,2004,53,4.91,21.97
198911,208022,Active,109021,NaN,NaN,S,7,1,9.708068e+05,142.75,2006,21,19.24,53.99
198912,208023,Active,109683,NaN,NaN,D,7,1,2.101869e+05,72.87,2006,54,8.46,60.59
198913,208024,Active,416462,NaN,NaN,D,8,1,4.555041e+05,247.00,2009,65,8.40,74.85
198914,208025,Active,658242,NaN,NaN,S,2,1,1.692746e+05,50.00,2012,23,23.98,32.62
198915,208026,Active,2538340,NaN,NaN,S,2,1,3.775266e+05,46.95,2001,23,27.42,37.89
198916,208027,Active,416662,NaN,NaN,D,15,1,1.183068e+05,120.00,2010,44,10.97,60.67

In [20]:
df.head(2)

,Order,File_Type,SKU_number,SoldFlag,SoldCount,MarketingType,ReleaseNumber,New_Release_Flag,StrengthFactor,PriceReg,ReleaseYear,ItemCount,LowUserPrice,LowNetPrice
0,2,Historical,1737127,0.0,0.0,D,15,1,682743.0,44.99,2015,8,28.97,31.84
1,3,Historical,3255963,0.0,0.0,D,7,1,1016014.0,24.81,2005,39,0.00,15.54

In [22]:
df["File_Type"]

0         Historical
1         Historical
2         Historical
3         Historical
4         Historical
5         Historical
6         Historical
7         Historical
8         Historical
9         Historical
10        Historical
11        Historical
12        Historical
13        Historical
14        Historical
15        Historical
16        Historical
17        Historical
18        Historical
19        Historical
20        Historical
21        Historical
22        Historical
23        Historical
24        Historical
25        Historical
26        Historical
27        Historical
28        Historical
29        Historical
             ...
198887        Active
198888        Active
198889        Active
198890        Active
198891        Active
198892        Active
198893        Active
198894        Active
198895        Active
198896        Active
198897        Active
198898        Active
198899        Active
198900        Active
198901        Active
198902        Active
198903        Active
198904        Active
198905        Active
198906        Active
198907        Active
198908        Active
198909        Active
198910        Active
198911        Active
198912        Active
198913        Active
198914        Active
198915        Active
198916        Active
Name: File_Type, Length: 198917, dtype: object

In [23]:
df.File_Type

0         Historical
1         Historical
2         Historical
3         Historical
4         Historical
5         Historical
6         Historical
7         Historical
8         Historical
9         Historical
10        Historical
11        Historical
12        Historical
13        Historical
14        Historical
15        Historical
16        Historical
17        Historical
18        Historical
19        Historical
20        Historical
21        Historical
22        Historical
23        Historical
24        Historical
25        Historical
26        Historical
27        Historical
28        Historical
29        Historical
             ...
198887        Active
198888        Active
198889        Active
198890        Active
198891        Active
198892        Active
198893        Active
198894        Active
198895        Active
198896        Active
198897        Active
198898        Active
198899        Active
198900        Active
198901        Active
198902        Active
198903        Active
198904        Active
198905        Active
198906        Active
198907        Active
198908        Active
198909        Active
198910        Active
198911        Active
198912        Active
198913        Active
198914        Active
198915        Active
198916        Active
Name: File_Type, Length: 198917, dtype: object